config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/detail'

  get 'details/company'
  get 'details/intro'
  get 'details/app1'
  get 'details/app2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  def company
  end

  def intro
  end

  def app1
  end

  def app2
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def detail
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/details/company.html.erb
    <!-- header start -->
    <header>
            <!-- navbar -->
            <nav class="navbar navbar-expand-lg fixed-top nav-menu bg-dark">
                <a href="" class="navbar-brand text-light text-uppercase">
                    <%= image_tag 'logo.png' %>
                </a>
                <button class="navbar-toggler nav-button" type="button"
                data-toggle="collapse" data-target="#myNavbar">
                <div class="bg-light line1"></div>
                <div class="bg-light line2"></div>
                <div class="bg-light line3"></div>
                </button>
            <div class="collapse navbar-collapse justify-content-end text-uppercase font-weight-bold" id="myNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="" class="nav-link m-2 menu-item nav-active">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link m-2 menu-item">MISSION</a>
                     </li>
                     <li class="nav-item">
                        <a href="" class="nav-link m-2 menu-item">SERVICE</a>
                     </li>
                     <li class="nav-item">
                         <a href="" class="nav-link m-2 menu-item">OFFICER</a>
                     </li>
                     <li class="nav-item">
                         <a href="" class="nav-link m-2 menu-item">COMPANY</a>
                     </li>
                     <li class="nav-item">
                          <a href="" class="nav-link m-2 menu-item">INFORMATION</a>
                    </li>
                    <li class="nav-item">
                          <a href="" class="nav-link m-2 menu-item">CONTACT</a>
                     </li>
                </ul>
            </div>
            </nav>

            <!-- banner -->
            <div class="text-light text-center">
                <%= image_tag 'work.jpg', class: "company" %>
            </div>

    </header>
    <!-- header end -->

    <!-- mission -->
    <section class="p-5 mission">
            <div class="container-fluid">

             <div class="row text-center">
                 <div class="col-m-4">
                      <h1 class="display-5 mt-5">Mission</h1>
                      <div class="underline mb-4"></div>
                      <p class="small">株式会社CIKSは、企業の経営課題解決を目的とした経営コンサルティング会社です。そのコンセプトは、「企業繁栄のための軍師的役割を果たすこと」であり企業ごとに異なる経営上の問題に優先順位をつけて、各専門家同士が連携し問題解決に挑みます。企業を脅かす「労務」「財務」「法律」に関わる潜在的リスクをディスクローズし、実績のある国家資格者がチームとなって解決して参ります。</p>
                  </div>
             </div>

             <div class="row text-center">
                 <div class="col-m-4">
                      <h1 class="display-5 mt-5">About Us</h1>
                      <div class="underline mb-4"></div>
                      <p class="small">株式会社CIKSは、企業の経営課題解決を目的とした経営コンサルティング会社です。そのコンセプトは、「企業繁栄のための軍師的役割を果たすこと」であり企業ごとに異なる経営上の問題に優先順位をつけて、各専門家同士が連携し問題解決に挑みます。企業を脅かす「労務」「財務」「法律」に関わる潜在的リスクをディスクローズし、実績のある国家資格者がチームとなって解決して参ります。</p>
                  </div>
             </div>

             <div class="row text-center">
                 <div class="col-m-4">
                      <h1 class="display-5 mt-5">Message</h1>
                      <div class="underline mb-4"></div>
                      <p class="small">中小企業を取り巻く環境は、その規模を問わず厳しくなっていく一方です。
                            経営者のビジョンを形にしていくためには、自社で「財務」「労務」「リスクマネジメント」を管理・運用できる体制を築くことが重要になってきます。弊社では経営者の社外ファシリテーターとして、経営ビジョンの実現に向けてあらゆる角度から事業運営をサポートして参ります。</p>
                 </div>
            </div>

        </div>
    </section>
     <!-- mission end -->

     <!-- service -->
     <section class="bg-secondary py-4">
            <div class="container-fluid">
                 <div class="row text-white text-center">
                     <div class="col m-4">
                       <h1 class="display-5 mb-4">SERVICE</h1>
                       <div class="underline mb-4"></div>
                       <p class="small">株式会社CIKSは、お客様のイノベーションを起こすために各分野の専門チームで<br>
                            「時代の変化に対応できる企業づくり」を行います。.</p>
                     </div>
                 </div>
                 <div class="row text-center">
                        <div class="col-lg-4 col-md-4 col-sm-6 my-5">
                                <div class="card border-0 card-shadow">
                                  <%= image_tag 'homeservice01.jpg' %>
                                     <div class="card-body">
                                         <h5 class="text-center font-weight-bold p-2">経営</h5>
                                         <a href="#" class="btn text-uppercase font-weight-bold service-button text-light">続きをみる</a>
                                     </div>
                                 </div>
                          </div>
                     <div class="col-lg-4 col-md-4 col-sm-6 my-5">
                          <div class="card border-0 card-shadow">
                                 <%= image_tag 'homeservice02.jpg' %>
                               <div class="card-body">
                                   <h5 class="text-center font-weight-bold p-2">人事・法務</h5>
                                   <a href="#" class="btn p-2 text-uppercase font-weight-bold service-button text-light">続きをみる</a>
                               </div>
                           </div>
                    </div>
                      <div class="col-lg-4 col-md-4 col-sm-6 my-5">
                            <div class="card border-0 card-shadow">
                                <%= image_tag 'homeservice03.jpg' %>
                                <div class="card-body">
                                    <h5 class="text-center font-weight-bold p-2">会計</h5>
                                    <a href="#" class="btn p-2 text-uppercase font-weight-bold service-button text-light">続きをみる</a>
                                 </div>
                            </div>
                        </div>

        </div>
      </div>
    </section>
    <!-- service end -->


    <!-- officer -->
    <section class="py-4">
            <div class="container-fluid">
                 <div class="row text-center">
                     <div class="col m-4">
                       <h1 class="display-4 mb-4">Officer</h1>
                       <div class="underline mb-4"></div>
                     </div>
                 </div>

            <div class="row text-center">
              <div class="col-lg-6 col-md-6 col-sm-4 my-5">
                <div class="card border-0 card-shadow">
                  <hi class="display-1">PICTURE</hi>
                   <div class="card-body">
                     <h5 class="text-uppercase font-weight-light p-2">Management</h5>
                    </div>
                  </div>
               </div>

                    <div class="col-lg-6 col-md-6 col-sm-4 my-5">
                      <div class="card border-0 card-shadow">
                        <hi class="display-1">PICTURE</hi>
                         <div class="card-body">
                           <h5 class="text-uppercase font-weight-light p-2">Management</h5>
                          </div>
                        </div>
                     </div>
                  </div>

        </div>
    </section>
     <!-- officer end -->

     <!-- company -->
    <section class="py-2">
            <div class="container-fluid">
                 <div class="row text-center">
                     <div class="col m-4">
                       <h1 class="display-5 mb-4">COMPANY</h1>
                       <div class="underline mb-4"></div>
                     </div>
                 </div>
                 <table>
                        <tbody>
                        <tr>
                        <th>社名</th>
                        <td>株式会社〇〇</td>
                        </tr>
                        <tr>
                        <th>役員</th>
                        <td>代表取締役：〇〇<br>
                        　取締役：〇〇<br>
                        　取締役：〇〇<br>
                        　取締役：〇〇</td>
                        </tr>
                        <tr>
                        <th>顧問</th>
                        <td>〇〇<br>
                        〇〇</td>
                        </tr>
                        <tr>
                        <th>設立</th>
                        <td>〇〇</td>
                        </tr>
                        <tr>
                        <th>所在地</th>
                        <td>〒000-0001<br class="sp"><span class="c_shozaichi">〇〇</span><br class="sp">〇〇</td>
                        </tr>
                        <tr>
                        <th>TEL</th>
                        <td>000-00000</td>
                        </tr>
                        <tr>
                        <th>関連会社</th>

                        </tr>
                        </tbody>
                        </table>

            </div>
    </section>

app/views/details/intro.html.erb
<header>
     <!-- navbar -->
     <nav class="navbar navbar-expand-lg fixed-top nav-menu">
             <a href="" class="navbar-brand text-uppercase">
             <span class="h2 font-weight-bold">ArtShare</span><span class="h1">App</span>
             </a>
             <button class="navbar-toggler nav-button" type="button"
             data-toggle="collapse" data-target="#myNavbar">
             <div class="bg-light line1"></div>change

             <div class="bg-light line2"></div>
             <div class="bg-light line3"></div>
             </button>
         <div class="collapse navbar-collapse ml-3 justify-content-between text-uppercase font-weight-bold" id="myNavbar">
             <ul class="navbar-nav">
                 <li class="nav-item">
                     <a href="" class="nav-link menu-item">HOME</a>
                 </li>
                  <li class="nav-item">
                     <a href="" class="nav-link menu-item">SYSTEM</a>
                  </li>
                  <li class="nav-item">
                      <a href="" class="nav-link menu-item">PHOTOS</a>
                  </li>
                 <li class="nav-item">
                       <a href="" class="nav-link menu-item">CONTACT</a>
                  </li>
             </ul>
         </div>
         </nav>

         <!-- banner -->
         <div class="text-muted text-md-bold text-center banner1">

             <h1 class="display-3 banner-heading">Share your drawings, pictures, and, beautiful staff. </h1>
             <p class="lead banner-par">List your art up on this art platform & make cash. </p>
         </div>

 </header>

 <section class="p-5 bg-success overview">
         <div class="container-fluid">
             <div class="row text-white text-center">
                 <div class="col-m-4">
                     <h1 class="display-5 mb-3">System</h1>
                     <div class="underline mb-4"></div>
                     <p class="lead">Matching those who want to lend the art crafts & those who want to rent like restraurant owner, hospital management.
                         We would like to make the platform for sharing art crafts & build the better places surrounded by beautiful things everyday.
                     </p>
                 </div>
             </div>

             <div class="row my-5">
                 <div class="col-md-4 text-center">
                     <i class="far fa-arrow-alt-circle-down fa-4x text-danger mb-4"></i>
                     <h1 class="text-white mb-4">Owner</h1>
                     <p class="text-danger">自分の作った作品をシェアすることができます。
                         自分の作品のオーナーとして、日常にアートが溢れる世界を一緒に作り出しましょう。
                     </p>
                 </div>
                 <div class="col-md-4 text-center">
                      <i class="fas fa-truck-moving fa-4x text-danger mb-4"></i>
                      <h1 class="text-white mb-4">Renter</h1>
                      <p class="text-danger">リストされているアート作品をお気軽にシェアリングできます。
                          日付を指定して、予約をすることができますので、色々な絵を期間で使い分けることができます。
                          いつもと代わり映えのする場所を作りましょう。
                      </p>
                  </div>
                  <div class="col-md-4 text-center">
                       <i class="far fa-handshake fa-4x text-danger mb-4"></i>
                       <h1 class="text-white mb-4">Platform</h1>
                       <p class="text-danger">本サービスは日常の場所にアートで彩りを与えるコミュニティーを提供します。
                         共により良い日常を作っていきましょう.

                       </p>
                  </div>
             </div>
         </div>
         <div class="container">
             <div class="row align-items-center">
                 <div class="col-lg-4 col-md-4 text-center">
                      <%= image_tag 'art.jpg', :width => "300", :class => "rounded-circle art-img" %>
                 </div>
                 <div class="col-lg-4 col-md-4 text-center">
                      <%= image_tag 'flower.jpg', :width => "300", :class => "rounded-circle art-img" %>
                 </div>
                 <div class="col-lg-4 col-md-4 text-center">
                      <%= image_tag 'art2.jpg', :width => "300", :class => "rounded-circle art-img" %>
                 </div>
             </div>
         </div>
     </section>

     <section class="m-5">
             <div class="container-fluid">

                 <div class="row text-info text-center">
                   <div class="col m-4">
                    <h1 class="display-5 mb-3"> PHOTOS </h1>
                    <div class="underline mb-4"></div>
                    <p class="lead">たくさんの作品がシェアリストに上がっています。</p>
                   </div>
                 </div>

                 <ul class="list-inline text-center text-uppercase font-weight-bold my-4">
                     <li class="list-inline-item gallery-list-item" data-filter="all">All <span class="mx-md-5 mx-3  text-muted"> | </span> </li>
                     <li class="list-inline-item gallery-list-item" data-filter="new">New <span class="mx-md-5 mx-3  text-muted"> | </span> </li>
                     <li class="list-inline-item gallery-list-item" data-filter="free">Drawings <span class="mx-md-5 mx-3  text-muted"> | </span> </li>
                     <li class="list-inline-item gallery-list-item" data-filter="pro">Pictures </li>
                 </ul>
                 <div class="containe-fluid">
                     <div class="d-flex flex-wrap justify-content-between">
                         <div class="filter new"><%= image_tag 'img1.jpg', :width => "300", :height => "300" %></div>
                         <div class="filter free"><%= image_tag 'img2.jpg', :width => "300", :height => "300" %></div>
                         <div class="filter pro"><%= image_tag 'img3.jpg', :width => "300", :height => "300" %></div>
                         <div class="filter new"><%= image_tag 'img4.jpg', :width => "300", :height => "300" %></div>
                         <div class="filter free"><%= image_tag 'img5.jpg', :width => "300", :height => "300" %></div>
                         <div class="filter pro"><%= image_tag 'img6.jpg', :width => "300", :height => "300" %></div>
                     </div>
                 </div>

             </div>
        </section>

<section class="contact p-5">
 <div class="container-fluid">
     <div class="row">
         <div class="col-lg-5 od-4">
             <h3 class="display-4 mb-5">Contact Us</h3>
             <form class="contact-form">
                 <div class="form-group py-4">
                     <input type="text" class="form-control my-2 p-2 input" placeholder="お名前">
                     <label for="name" class="label">Name</label>
                 </div>

                 <div class="form-group py-4">
                     <input type="email" class="form-control my-2 p-2 input" placeholder="Email">
                     <label for="email" class="label">Email</label>
                  </div>

                  <div class="form-group py-4">
                     <input type="message" class="form-control my-2 p-2 input" placeholder="メッセージ">
                     <label for=",essage" class="label">Message</label>
                  </div>

                 <div class="form-group py-4 my-4">
                      <input type="checkbox" checked>
                      <label for="check" class="text-white">Send Message</label>
                 </div>
                 <button type="submit" class="btn btn-block p-2 font-weight-bold text-uppercase submit-button">送信</button>

             </form>
         </div>
     </div>
 </div>
</section>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>

    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
  </head>

  <body>

      <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/navbar' %>

<section class="p-sm-5 p-2 bg-secondary">
  <div class="container-fluid">
    <div class="row">
      <div class="col text-center mb-5">
        <h1 class="text-success display-3">About Me</h1>
        <p class="lead text-light">簡単な自己紹介を下記にまとめました</p>
      </div>
    </div>

  <div class="row text-center">
    <div class="col-lg-4 sm-10 mx-auto mb-4">
      <div class="card" style="width: 18rem;">
        <%= image_tag 'basket.jpg', :size=>"286x300" %>
        <div class="card-body">
          <h5 class="card-title text-center text-success mb-4">バスケット</h5>
          <p class="card-text text-secondary">小学校から高校まで部活動していました。観戦もよくしています。</p>
        </div>
      </div>
    </div>

      <div class="col-lg-4 sm-10 mx-auto mb-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag 'piano.jpg', :size=>"286x300" %>
          <div class="card-body">
            <h5 class="card-title text-center text-success mb-4">ピアノ</h5>
            <p class="card-text text-secondary">2018年より練習を開始して楽しく継続しています。</p>
          </div>
        </div>
      </div>

      <div class="col-lg-4 sm-10 mx-auto mb-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag 'book.jpg', :size=>"286x300" %>
          <div class="card-body">
            <h5 class="card-title text-center text-success mb-4">読書</h5>
            <p class="card-text text-secondary">時間があれば読書をしています。科学系が好きです。</p>
          </div>
        </div>
      </div>

    </div>

  </div>
</section>

app/views/pages/detail.html.erb
<%= render 'shared/navbar' %>

<!-- projects -->
  <div class="container-fluid mt-4">
      <div class="row">
          <div class="col text-center mb-3">
            <h1 class="text-info display-5">開発例</h1> <hr>
            <p class="load text-secondary">これまでの学習で開発した WEBページ ＆ アプリケーション です。</p>
          </div>
      </div>

      <div class="row">
        <div class="col-lg-3 col-sm-6 mt-3">
          <%= image_tag 'company.png', :size=>"250x250" %>

          <h4 class="my-3 text-info text-center">企業紹介LP</h4>
          <%= link_to '詳細ページへ', '/details/company', class: "btn btn-success m-3 text-center" %>
          <p class="text-muted p-3 mb-5">
            - HTML <br> - CSS <br> - Bootstrap <hr>
            クラウドソーシングのプロジェクトを参考に作成しました。
          </p>
        </div>

      <div class="col-lg-3 col-md-3 col-sm-6 mt-3">
          <%= image_tag 'intro.png', :size=>"250x250" %>
          <h4 class="my-3 text-info text-center">アプリ紹介LP</h4>
          <%= link_to '詳細ページへ', '/details/intro', class: "btn btn-success m-3 text-center" %>
          <p class="text-muted p-3">
            - HTML <br> - CSS <br> - jQuery <br> - Bootstrap <hr>
            アプリ紹介用のページを自作しました。
            画面に動きをつけた構成になっています。
          </p>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 mt-3">
          <%= image_tag 'app1.png', :size=>"250x250" %>
          <h4 class="my-3 text-info text-center">アートシェアアプリ</h4>
          <%= link_to 'GitHubへ', 'https://github.com/YutaSakamoto/ArtShare', class: "btn btn-success m-3 text-center" %>
          <p class="text-muted p-3">
            - Ruby on Rails <br> - ユーザー登録機能 <br> - 作品投稿機能 <br> - 予約機能
            <br> - Google map 表示機能 <br> - 予約通知機能 <br> - stripe 支払い機能 <hr>
            各々の実装方法を調べながら作成しました。
            シェアリングサービスに必要だと思われる機能を考えて工夫しました。
            stripe や Google map API の実装に苦労しました。
          </p>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 mt-3">
          <%= image_tag 'app2.png', :size=>"250x250" %>
          <h4 class="my-3 text-info text-center">アイデア共有アプリ</h4>
          <%= link_to 'アプリへ', 'https://ideahacks22222.herokuapp.com/', class: "btn btn-success m-3 " %>
          <p class="text-muted p-3">
            - Ruby on Rails <br> - ユーザー登録機能 <br> - アイデア投稿・募集機能 <br>
            - カテゴリー分け機能 <br> - お気に入り機能 <br> - フォロー機能 <br>
            - チャット機能 <br> - 検索機能 <hr>
            カテゴリー分け、検索機能の実装を頑張りました。
          </p>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

  <div class="container-fluid">

    <div class="row justify-content-center align-items-center">

        <div class="col-sm-12 text-center banner">
          <h1 class="display-2 text-capitalize text-white mb-3">bocoming better with <span class="text-warning">programming</span> </h1>
          <h2 class="font-weight-light text-white font-italic">
            This website is made for showing my brief history of learning programming <br>
            from July of 2018.  My best wish is achieve my own goal by using <br>
            with programming skills & knowledge. <br>
            This web site is made by Ruby on rails & the each front page represents my struggle of studing skills.
          </h2>
        </div>

    </div>

    </div>


<!-- skill -->
<section class="bg-light mt-2 p-3">
  <div class="container-fluid">
    <div class="row">
      <div class="col text-center mb-3">
        <h1 class="text-warning display-4">Skills</h1>
        <p class="lead text-secondary">2018年から身につけたスキル一覧</p>
      </div>

      <div class="row text-center">
        <div class="col-lg-4 col-md-4 col-sm-10 mx-auto mb-5">
          <i class="fas fa-desktop fa-5x text-warning mb-3"></i>
          <h2 class="text-secondary">HTML & CSS & BOOTSTRAP</h2>
          <p class="text-muted my-4">Bootstrapを使用し、迅速なフロントページの開発＆レスポンシブ対応についてのスキルを身につけました。</p>
          <a href="#" class="btn btn-outline-warning">Learn More</a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-10 mx-auto mb-5">
            <i class="far fa-edit fa-5x text-warning mb-3"></i>
            <h2 class="text-secondary">Ruby on Rails </h2> <br>
            <p class="text-muted my-4">Rails を使用した、バックエンドの開発知識 & 実装
            アイデア共有サイトや美術作品の個人間シェアリングサービスをゼロから開発しました</p>
            <a href="#" class="btn btn-outline-warning">Learn More</a>
       </div>
       <div class="col-lg-4 col-md-4 col-sm-10 mx-auto mb-5">
              <i class="fas fa-cogs fa-5x text-warning mb-3"></i>
              <h2 class="text-secondary">Others</h2> <br>
              <p class="text-muted my-4">Python + Django を使用したwebアプリケーション　および　ブロックチェーン＆AIを少しづつ学んでいます</p>
              <a href="#" class="btn btn-outline-warning">Learn More</a>
       </div>
      </div>
    </div>

  </div>
</section>

<!-- progress -->
<section class="p-4">
  <div class="container-fluid">
      <div class="row">
          <div class="col text-center mb-3">
            <h1 class="text-warning display-5">スキル進捗</h1>
            <p class="lead text-secondary">各スキルを表示しています。</p>
          </div>
        </div>

      <div class="row justify-content-center">
       <div class="col-lg-6 col-sm-10 text-secondary">
        <h2>HTML</h2>
          <div class="progress bg-secondary mb-3">
            <div class="progress-bar" style="width: 70%">
              70%
            </div>
          </div>
          <h2>CSS</h2>
          <div class="progress bg-secondary mb-3">
            <div class="progress-bar bg-danger" style="width: 50%">
              50%
            </div>
          </div>
          <h2>jQuery</h2>
          <div class="progress bg-secondary mb-3">
            <div class="progress-bar bg-warning" style="width: 50%">
              50%
            </div>
          </div>
          <h2>Bootstrap</h2>
          <div class="progress bg-secondary mb-3">
            <div class="progress-bar bg-success" style="width: 70%">
              70%
            </div>
          </div>
          <h2>Ruby on Rails</h2>
          <div class="progress bg-secondary mb-3">
            <div class="progress-bar bg-info" style="width: 85%">
              85%
            </div>
          </div>

       </div>
      </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<!-- NAVBAR
================================================== -->
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-light" href="/">Yuta</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'About', pages_about_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Project', pages_detail_path, class: "nav-link text-white" %>
      </li>
    </ul>
  </div>
</nav>